### PR TITLE
feat: fix result for "ABAC with policy rule" model

### LINKED ISSUE #33: [bug] the editor result for "ABAC with policy rule" is wrong
See: https://editor.casbin.org/#9XJPDZPZ4 , the Java (aka casbin-java-cli) engine result is different from the Node.js engine result. The Node.js result is correct. The Java one is wrong.

Java:

image

Node.js:

image

### PR DESCRIPTION
**Pull request by sukidayou**
Fix: https://github.com/jcasbin/casbin-java-cli/issues/33

### CODE REVIEW

**Comment by hsluoyz** [comment]
@tangyang9464 @imp2002 please review

File: src/test/java/org/casbin/ClientTest.java [hunk 1]
```diff
@@ -319,5 +319,8 @@ public void resetBasicWithResourcesPolicyFile() {
         }
     }
 
-
+    @Test
+    public void testABACRule() {
+        assertEquals(Client.run(new String[]{"enforce", "-m", "examples/abac_rule_model.conf", "-p", "examples/abac_rule_policy.csv", "{Age: 30}", "/data1", "read"}), "{\"allow\":true,\"explain\":null}");
```
Comment (hsluoyz) [inline src/test/java/org/casbin/ClientTest.java:324]: reason should not be null

**Review by hsluoyz — CHANGES_REQUESTED** [review]

**Review by hsluoyz — APPROVED** [review]
